language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: fX0xybLZxSHw2bvq7XmeN+kgzLS4yBeFSIj7GhqHnrac6+Ot44Yon8DtJ9yeRJd8JmATfk5ol0d2ZdfR66RYPU86dG8o321D4pX6g1XSsPTtcO7SJyd70xkYvW2/PZUHARKWgzZ1q5bugHbuSvOAaw145V6L5fU5HZBApt4EtJNiz6NISCKpOO/yOkDh6G3ycK5KrZPue7oxbe/ze+lXxmKL6DLnJZHmsD/KmiZ7DyNgeYTClJB7X4wZ+7QO1njSFmzc9tNmoB65m+Sj34ex7DYGCs+v89ufFifYiH8mlh5qukC88wjGEE5DVZRZDFLjdpjIFCS7qvZVotuqMMXu2AZlVn5ljcsnKVg+sKNVjfwL0qE/cCnPNZXOslLhiYBTiuAQy/G9yrMS4zK5B7fgFQaVdnWcG3B2mi052ToiK6z8u2HM8WzwHDPN1K/8hyiuw2M7qBBod4iLgLTol9K3d5E9IVyQKYcfhdSUfvxXW92tbuhHeOAfyyxytVIj2Jfen7rtwn9cnM42vNvutYHMKExzp2PAGaRQJAh+0dEYgixV9KxtNziqrYR39QxN7apmS/3u/xAOIlzrmCjpEXzhOl+GV0XfwIb9R901eRN1gGQ3X29JQKEg4uadoby+BV8aZLugMnnrFqUYw5miRas5zPDdB1HrAgoLbXGS15/dM/Q=
  run: rake db:migrate
